version: "3.8"

services:
  e2e:
    image: python:3.12.0-alpine3.18
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - /Users/vitalykamynin/projects/PythonTreloAPI_n_UI
    command: /bin/sh -c "ls -ls && pytest -m healthcheck -alluredir=allure-results"
    working_dir: /Users/vitalykamynin/projects/PythonTreloAPI_n_UI

#    environment:
#      - DB_USER=${DB_USER}
#      - DB_PASS=${DB_PASS}
#      - DB_NAME=${DB_NAME}
#      - DB_PORT=${DB_PORT}
#      - DB_HOST=${DB_HOST}

