services:
  e2e:
    image: python:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/automation
    command: /bin/bash -c "pip3 install -r requirements.txt && ls -ls && pytest -m health --alluredir=allure-results"
#    command: /bin/sh -c "ls -ls"
    working_dir: /automation

#    environment:
#      - DB_USER=${DB_USER}
#      - DB_PASS=${DB_PASS}
#      - DB_NAME=${DB_NAME}
#      - DB_PORT=${DB_PORT}
#      - DB_HOST=${DB_HOST}

