services:
  e2e:
    image: python:3.12.0-alpine3.18
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/bin/automation
    command: /bin/sh -c "ls -ls && pytest --version && pytest -m health --alluredir=allure-results"
#    command: /bin/sh -c "ls -ls"
    working_dir: /usr/bin/automation

#    environment:
#      - DB_USER=${DB_USER}
#      - DB_PASS=${DB_PASS}
#      - DB_NAME=${DB_NAME}
#      - DB_PORT=${DB_PORT}
#      - DB_HOST=${DB_HOST}

